# Generated by Django 4.0.4 on 2022-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_remove_heartdata_bpquestion1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickHeartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], verbose_name='Gender')),
                ('activity', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Breathlessness during activity')),
                ('rest', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Breathlessness at rest')),
                ('night', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Awake by Breathlessness at night')),
                ('exercise', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Exercise induced angina (chest pain after exercise)')),
                ('diabetes', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Diabetic')),
                ('bp', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Blood Pressure')),
                ('cyanosis', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Cyanosis')),
                ('clubbing', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Clubbing')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
