# Generated by Django 4.0.4 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_quickheartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickheartdata',
            name='probability',
            field=models.FloatField(null=True),
        ),
    ]
